{
    'name': 'AypaTech AI Assistant',
    'summary': 'Agentic AI assistant for Odoo with chat, MCP server, skills, chatter mentions, automation and schedules',
    'description': """
AypaTech AI Assistant brings an agentic AI assistant into the Odoo backend.

- Chat with agents from a floating window, the systray or a full-screen view
- OpenAI, Anthropic and Google Gemini providers out of the box
- Built-in MCP server so external AI clients can work with your Odoo data
- Skills, spaces, approvals and per-user sharing
- @mention agents in chatter and let them draft messages for you
- Run agents from server actions, automation rules and schedules
    """,
    'version': '20.0.1.0.0',
    'category': 'Productivity',
    'license': 'OPL-1',
    'author': 'AypaTech',
    'maintainer': 'AypaTech',
    'website': 'https://aypatech.com',
    'depends': [
        'base_setup',
        'web_tour',
        'web',
        'mail',
        'bus',
        'attachment_indexation',
        'html_editor',
        'base_automation',
    ],
    'external_dependencies': {
        'python': ['croniter'],
    },
    'data': [
        'webutils/views/res_config_settings.xml',
        'mcp/data/tool.xml',
        'mcp/data/prompt.xml',
        'mcp/security/ir.access.csv',
        'mcp/views/key.xml',
        'mcp/views/generate_key.xml',
        'mcp/views/show_key.xml',
        'mcp/views/log.xml',
        'mcp/views/notification.xml',
        'mcp/views/session.xml',
        'mcp/views/tool.xml',
        'mcp/views/prompt.xml',
        'mcp/views/connect.xml',
        'mcp/views/res_users.xml',
        'mcp/views/playground.xml',
        'mcp/views/menu.xml',
        'ai/security/ir.access.csv',
        'ai/data/provider.xml',
        'ai/data/model.xml',
        'ai/data/agent.xml',
        'ai/data/ir_model.xml',
        'ai/data/ir_cron.xml',
        'ai/data/space.xml',
        'ai/views/ir_model.xml',
        'ai/views/provider.xml',
        'ai/views/model.xml',
        'ai/views/agent.xml',
        'ai/views/approval.xml',
        'ai/views/mcp_tool_log.xml',
        'ai/views/space.xml',
        'ai/views/session.xml',
        'ai/views/chat.xml',
        'ai/views/res_users.xml',
        'ai/views/res_config_settings.xml',
        'ai/views/menu.xml',
        'skills/security/ir.access.csv',
        'skills/data/skill.xml',
        'skills/views/skill.xml',
        'skills/views/menu.xml',
        'chatter/data/space.xml',
        'chatter/data/skill.xml',
        'chatter/views/ai_agent.xml',
        'chatter/views/skill.xml',
        'chatter/views/mail_compose_message.xml',
        'automation/data/ir_actions.xml',
        'automation/views/ir_actions_server.xml',
        'automation/views/base_automation.xml',
        'automation/views/menu.xml',
        'schedule/security/ir.access.csv',
        'schedule/data/space.xml',
        'schedule/views/schedule.xml',
        'schedule/views/session.xml',
        'schedule/views/menu.xml',
    ],
    'demo': [
        'ai/demo/agent.xml',
        'ai/demo/session.xml',
        'skills/demo/skill.xml',
        'automation/demo/ir_actions_server.xml',
        'automation/demo/base_automation.xml',
        'schedule/demo/schedule.xml',
        'schedule/demo/session.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'aypatech_ai_assistant/static/src/webutils/core/block_progress/*',
            ('after', 'web/static/src/views/list/list_arch_parser.js', 'aypatech_ai_assistant/static/src/webutils/views/list/list_arch_parser.js'),
            ('after', 'web/static/src/views/list/list_renderer.xml', 'aypatech_ai_assistant/static/src/webutils/views/list/list_renderer.xml'),
            ('after', 'web/static/src/views/fields/many2one/many2one_field.js', 'aypatech_ai_assistant/static/src/webutils/views/fields/many2one/many2one.js'),
            ('after', 'web/static/src/views/fields/x2many/x2many_field.js', 'aypatech_ai_assistant/static/src/webutils/views/fields/x2many/x2many.js'),
            'aypatech_ai_assistant/static/src/webutils/tour/**/*',
            'aypatech_ai_assistant/static/src/webutils/webclient/**/*',
            'aypatech_ai_assistant/static/src/webutils/views/module_availability.js',
            'aypatech_ai_assistant/static/src/webutils/views/fields/json/*',
            'aypatech_ai_assistant/static/src/webutils/views/fields/module_link/*',
            'aypatech_ai_assistant/static/src/webutils/views/fields/text_icons/*',
            'aypatech_ai_assistant/static/src/webutils/views/fields/selection_icons/*',
            'aypatech_ai_assistant/static/src/mcp/core/message.xml',
            'aypatech_ai_assistant/static/src/mcp/playground/**/*',
            'aypatech_ai_assistant/static/lib/ai/markdown-it/markdown-it.js',
            'aypatech_ai_assistant/static/src/ai/chat/**/*',
            'aypatech_ai_assistant/static/src/ai/components/**/*',
            'aypatech_ai_assistant/static/src/ai/core/**/*',
            'aypatech_ai_assistant/static/src/ai/views/adjust.js',
            'aypatech_ai_assistant/static/src/ai/views/context.js',
            'aypatech_ai_assistant/static/src/ai/views/fields/**/*',
            'aypatech_ai_assistant/static/src/ai/views/form/**/*',
            'aypatech_ai_assistant/static/src/ai/views/kanban/**/*',
            'aypatech_ai_assistant/static/src/ai/views/list/**/*',
            'aypatech_ai_assistant/static/src/ai/webclient/**/*',
            ('remove', 'aypatech_ai_assistant/static/src/ai/**/*.dark.scss'),
            'aypatech_ai_assistant/static/src/skills/**/*',
            'aypatech_ai_assistant/static/src/chatter/**/*',
            'aypatech_ai_assistant/static/src/schedule/views/fields/**/*',
            'aypatech_ai_assistant/static/src/schedule/chat/**/*',
        ],
        'web.assets_backend_lazy': [
            'aypatech_ai_assistant/static/src/ai/views/graph/**/*',
            'aypatech_ai_assistant/static/src/ai/views/pivot/**/*',
        ],
        'web.assets_web_dark': [
            'aypatech_ai_assistant/static/src/ai/**/*.dark.scss',
        ],
        'web.assets_tests': [
            'aypatech_ai_assistant/static/tests/mcp/tours/**/*',
            'aypatech_ai_assistant/static/tests/chatter/tours/chatter_tour.js',
            'aypatech_ai_assistant/static/tests/schedule/tours/schedule_tour.js',
        ],
        'web.assets_unit_tests': [
            'aypatech_ai_assistant/static/tests/webutils/**/*',
            'aypatech_ai_assistant/static/tests/mcp/**/*.test.js',
            'aypatech_ai_assistant/static/tests/ai/**/*.test.js',
            'aypatech_ai_assistant/static/tests/skills/**/*.test.js',
            'aypatech_ai_assistant/static/tests/chatter/**/*.test.js',
            'aypatech_ai_assistant/static/tests/schedule/**/*.test.js',
        ],
    },
    'images': [
        'static/description/banner.png',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': '_post_init_hook',
}
